version: '3.8'

services:
  my-service:
    container_name: my-service
    restart: unless-stopped
    env_file: .env
    build:
      target: production
      context: .
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
